import type { Entry } from './types'

// ponytail: data awal buat dev lokal. Nanti ganti ke Supabase lewat 0001_init.sql.
export function seed(): Entry[] {
  const now = Date.now()
  const t = (offset: number) => new Date(now - offset * 1000).toISOString()

  return [
    {
      id: 'seed-1',
      kind: 'site',
      title: 'luvus.dev',
      url: 'https://luvus.dev',
      description: 'Portfolio builder buat anak IF yang males desain.',
      category: 'Tool / Utility',
      has_chatbot: true,
      meta: {
        m_fitur: 'Drag-drop section, export ke Vercel',
        m_usecase: 'Bikin portofolio cepat',
        m_pricing: 'Freemium',
        m_platform: 'Web',
      },
      upvotes: 12,
      clicks: 30,
      reports: 0,
      hidden: false,
      created_at: t(5000),
    },
    {
      id: 'seed-2',
      kind: 'site',
      title: 'orkata.co',
      url: 'https://orkata.co',
      description: 'Naruh ide & cerita panjang buat dibaca pelan-pelan.',
      category: 'Writing / Content',
      has_chatbot: true,
      meta: {
        m_fitur: 'Editor fokus, word count',
        m_usecase: 'Nulis catatan harian',
        m_pricing: 'Gratis',
        m_platform: 'Web',
      },
      upvotes: 8,
      clicks: 14,
      reports: 0,
      hidden: false,
      created_at: t(4000),
    },
    {
      id: 'seed-3',
      kind: 'site',
      title: 'moldingflask.vercel.app',
      url: 'https://moldingflask.vercel.app',
      description: 'Koleksi prompt AI yang rapi dan bisa dicopy.',
      category: 'AI / ML',
      has_chatbot: false,
      meta: null,
      upvotes: 20,
      clicks: 55,
      reports: 0,
      hidden: false,
      created_at: t(3000),
    },
    {
      id: 'seed-4',
      kind: 'site',
      title: 'pamerin.lol',
      url: 'https://pamerin.lol',
      description: 'Tempat pamer project receh sampai serius.',
      category: 'Portfolio / Showcase',
      has_chatbot: false,
      meta: null,
      upvotes: 5,
      clicks: 9,
      reports: 0,
      hidden: false,
      created_at: t(2000),
    },
    {
      id: 'seed-5',
      kind: 'site',
      title: 'kuliahyuk.vercel.app',
      url: 'https://kuliahyuk.vercel.app',
      description: 'Ringkasan kuliah IF biar gak panik sebelum UTS.',
      category: 'Edu / Pembelajaran',
      has_chatbot: false,
      meta: null,
      upvotes: 3,
      clicks: 7,
      reports: 0,
      hidden: false,
      created_at: t(1000),
    },
    {
      id: 'seed-6',
      kind: 'prompt',
      title: 'Bikin chatbot FAQ dari PDF',
      description: 'Prompt buat bikin bot tanya-jawab dari dokumen.',
      body: 'Baca {{pdf}} lalu buat jawaban FAQ singkat per pertanyaan yang mungkin ditanyakan user. Jawab pakai bahasa yang sama dengan dokumen.',
      variables: '{{pdf}}',
      category: 'Chatbot / Assistant',
      has_chatbot: true,
      meta: {
        m_model: 'GPT-4o',
        m_variables: '{{pdf}}',
        m_usecase: 'Customer support otomatis',
        m_output: 'List Q&A dari dokumen',
      },
      upvotes: 15,
      clicks: 40,
      reports: 0,
      hidden: false,
      created_at: t(600),
    },
    {
      id: 'seed-7',
      kind: 'prompt',
      title: 'Security audit assistant',
      description: 'Prompt buat review keamanan kode.',
      body: 'Review {{code}} untuk celah keamanan umum (XSS, SQLi, auth bypass). Berikan tiap temuan beserta fix singkat.',
      variables: '{{code}}',
      category: 'Coding',
      has_chatbot: false,
      meta: null,
      upvotes: 9,
      clicks: 22,
      reports: 0,
      hidden: false,
      created_at: t(400),
    },
    {
      id: 'seed-8',
      kind: 'prompt',
      title: 'Threat model generator',
      description: 'Prompt buat susun threat model dari deskripsi sistem.',
      body: 'Dari deskripsi {{system}}, hasilkan threat model dengan STRIDE: tiap kategori beri contoh ancaman dan mitigasinya.',
      variables: '{{system}}',
      category: 'Coding',
      has_chatbot: false,
      meta: null,
      upvotes: 6,
      clicks: 11,
      reports: 0,
      hidden: false,
      created_at: t(200),
    },
  ]
}
